export const RECRUIT_JOBS_CATEGORY = {
  RELIGION: 'RELIGION',
  LECTURER: 'LECTURER',
  ETC: 'ETC',
  ART_ORGANIZATION: 'ART_ORGANIZATION',
} as const;
export type RECRUIT_JOBS_CATEGORY = (typeof RECRUIT_JOBS_CATEGORY)[keyof typeof RECRUIT_JOBS_CATEGORY];
